name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      - name: Build swiftshader
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: swiftshader-linux
          path: build/Linux
